version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ogsanalysis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ogs_db
    ports:
      - "5432:5432" # to connect with psql from WSL while container is running
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ogsanalysis_app
    volumes:
      - .:/app
      - /home/ryanh/ogs_data:/data:ro
    environment:
      # Internal container-to-container connection string
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ogs_db
    depends_on:
      - db
    command: sleep infinity

volumes:
  dbdata:
